#!/bin/bash
# generate-themes.sh
# TEK palette dosyasından tüm app-specific config formatlarını üretir.
#
# Girdi:   ~/.config/palette/palette.sh  (matugen'in yazdığı source of truth)
# Çıktı:   ~/.config/hypr/colors.conf
#          ~/.config/waybar/colors.css
#          ~/.config/kitty/colors.conf
#          ~/.config/mako/config
#
# Yeni app eklemek istersen: aşağıya bir "─── X ───" bloğu ekle, P_* değişkenlerini
# o app'in kendi sözdizimiyle dök. matugen'a dokunma.

set -eu

PAL="${1:-$HOME/.config/palette/palette.sh}"
[ -f "$PAL" ] || { echo "No palette: $PAL" >&2; exit 1; }
# shellcheck disable=SC1090
source "$PAL"

# Hyprland'in `rgb(AABBCC)` formatı için `#` stripping:
strip() { printf '%s' "${1#\#}"; }

# ─── Hyprland ────────────────────────────────────────────
cat > "$HOME/.config/hypr/colors.conf" <<EOF
# Auto-generated by generate-themes.sh from ~/.config/palette/palette.sh
# Do not edit by hand.

\$primary    = rgb($(strip "$P_PRIMARY"))
\$secondary  = rgb($(strip "$P_SECONDARY"))
\$tertiary   = rgb($(strip "$P_TERTIARY"))
\$surface    = rgb($(strip "$P_SURFACE"))
\$on_surface = rgb($(strip "$P_ON_SURFACE"))
\$background = rgb($(strip "$P_BACKGROUND"))
\$outline    = rgb($(strip "$P_OUTLINE"))
\$error      = rgb($(strip "$P_ERROR"))
\$accent     = \$primary

general {
    col.active_border   = \$accent \$tertiary 45deg
    col.inactive_border = \$outline
}
EOF

# ─── Waybar ─────────────────────────────────────────────
cat > "$HOME/.config/waybar/colors.css" <<EOF
/* Auto-generated by generate-themes.sh from ~/.config/palette/palette.sh */
/* Do not edit by hand. */

@define-color primary       ${P_PRIMARY};
@define-color on-primary    ${P_ON_PRIMARY};
@define-color secondary     ${P_SECONDARY};
@define-color on-secondary  ${P_ON_SECONDARY};
@define-color tertiary      ${P_TERTIARY};
@define-color surface       ${P_SURFACE};
@define-color on-surface    ${P_ON_SURFACE};
@define-color background    ${P_BACKGROUND};
@define-color outline       ${P_OUTLINE};
@define-color error         ${P_ERROR};
EOF

# ─── Kitty ──────────────────────────────────────────────
cat > "$HOME/.config/kitty/colors.conf" <<EOF
# Auto-generated by generate-themes.sh from ~/.config/palette/palette.sh

background            ${P_SURFACE}
foreground            ${P_ON_SURFACE}
selection_background  ${P_PRIMARY}
selection_foreground  ${P_ON_PRIMARY}
cursor                ${P_PRIMARY}
cursor_text_color     ${P_ON_PRIMARY}
url_color             ${P_TERTIARY}

active_border_color   ${P_PRIMARY}
inactive_border_color ${P_OUTLINE}
bell_border_color     ${P_ERROR}

active_tab_foreground   ${P_ON_PRIMARY}
active_tab_background   ${P_PRIMARY}
inactive_tab_foreground ${P_ON_SURFACE}
inactive_tab_background ${P_SURFACE}

color0  ${P_SURFACE}
color1  ${P_ERROR}
color2  ${P_TERTIARY}
color3  ${P_SECONDARY}
color4  ${P_PRIMARY}
color5  ${P_TERTIARY}
color6  ${P_SECONDARY}
color7  ${P_ON_SURFACE}
color8  ${P_OUTLINE}
color9  ${P_ERROR}
color10 ${P_TERTIARY}
color11 ${P_SECONDARY}
color12 ${P_PRIMARY}
color13 ${P_TERTIARY}
color14 ${P_SECONDARY}
color15 ${P_ON_SURFACE}
EOF


# ─── Mako (notification daemon, terminal-aesthetic) ────
# SwayNC silindi. Terminal TUI zen'e uygun: sharp, flat, monospace, kısa.
mkdir -p "$HOME/.config/mako"
cat > "$HOME/.config/mako/config" <<EOF
# Auto-generated by generate-themes.sh from ~/.config/palette/palette.sh
sort=-time
layer=overlay
anchor=top-right
width=340
height=110
margin=10
padding=10,14
border-size=1
border-radius=0
default-timeout=5000
ignore-timeout=1
icons=0
font=CaskaydiaCove Nerd Font 10

background-color=${P_SURFACE}
text-color=${P_ON_SURFACE}
border-color=${P_OUTLINE}
progress-color=over ${P_PRIMARY}

[urgency=low]
border-color=${P_OUTLINE}

[urgency=normal]
border-color=${P_OUTLINE}

[urgency=critical]
border-color=${P_ERROR}
default-timeout=0
EOF
