#!/bin/bash
# gpu-detect.sh — lspci'ye göre GPU tespit, paketleri kurar, Hyprland env conf'ı üretir.
#
# Kurulum:  bash gpu-detect.sh install     # paketleri kurar (sudo ister)
# Env only: bash gpu-detect.sh env         # sadece ~/.config/hypr/gpu-env.conf yazar
#
# Desteklenen: Nvidia (Ada/Blackwell nvidia-open zorunlu) / AMD / Intel.
# Taze sistem kurulumunda çağrılır, sonra Hyprland env'i otomatik doğru olur.

set -eu

MODE="${1:-env}"    # install | env

# ── Tespit ─────────────────────────────────────────────────
detect_gpu() {
    local line
    line=$(lspci | grep -iE 'vga|3d|display' | head -1)
    case "$line" in
        *NVIDIA*|*nvidia*) echo "nvidia" ;;
        *AMD*|*ATI*|*Radeon*) echo "amd" ;;
        *Intel*|*intel*) echo "intel" ;;
        *) echo "unknown" ;;
    esac
}

GPU=$(detect_gpu)
echo "GPU tespit edildi: $GPU"

# ── Paket kurulumu ─────────────────────────────────────────
install_packages() {
    case "$GPU" in
        nvidia)
            # Blackwell/Ada RTX 40-50 → nvidia-open zorunlu. Eski kartlar da
            # nvidia-open destekler (Turing+). Proprietary nvidia modüllerinden
            # kaç: CUDA ve display için nvidia-open + nvidia-utils yeter.
            sudo pacman -S --noconfirm --needed \
                nvidia-open nvidia-utils egl-wayland libva-nvidia-driver nvidia-settings
            ;;
        amd)
            # mesa + Vulkan (radv) ana driver. AMDVLK opsiyonel, gerekmez.
            # Not: `mesa-vdpau` Arch'tan kaldırıldı (VDPAU desteği mesa içinde).
            sudo pacman -S --noconfirm --needed \
                mesa vulkan-radeon libva-mesa-driver
            ;;
        intel)
            # intel-media-driver (Gen8+) modern, `libva-intel-driver` eski Gen7-.
            # Yeni laptop'larda ilki yeterli.
            sudo pacman -S --noconfirm --needed \
                mesa vulkan-intel intel-media-driver
            ;;
        *)
            echo "Uyarı: GPU tespit edilemedi. Manuel paket kurulumu gerekir." >&2
            return 1
            ;;
    esac
}

# ── Hyprland env dosyası ──────────────────────────────────
write_env() {
    local out="$HOME/.config/hypr/gpu-env.conf"
    mkdir -p "$(dirname "$out")"
    case "$GPU" in
        nvidia)
            cat > "$out" <<EOF
# Auto-generated by gpu-detect.sh — Nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = NVD_BACKEND,direct
env = ELECTRON_OZONE_PLATFORM_HINT,auto
EOF
            ;;
        amd)
            cat > "$out" <<EOF
# Auto-generated by gpu-detect.sh — AMD
env = LIBVA_DRIVER_NAME,radeonsi
env = VDPAU_DRIVER,radeonsi
env = ELECTRON_OZONE_PLATFORM_HINT,auto
EOF
            ;;
        intel)
            cat > "$out" <<EOF
# Auto-generated by gpu-detect.sh — Intel
env = LIBVA_DRIVER_NAME,iHD
env = VDPAU_DRIVER,iHD
env = ELECTRON_OZONE_PLATFORM_HINT,auto
EOF
            ;;
        *)
            : > "$out"
            ;;
    esac
    echo "Yazıldı: $out"
}

case "$MODE" in
    install) install_packages && write_env ;;
    env)     write_env ;;
    *) echo "usage: $0 [install|env]"; exit 1 ;;
esac
